[package]
name = "bittle"
version = "0.2.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
description = "A library for working with small and cheap bit sets and masks"
documentation = "https://docs.rs/bittle"
readme = "README.md"
homepage = "https://github.com/udoprog/bittle"
repository = "https://github.com/udoprog/bittle"
license = "MIT/Apache-2.0"
keywords = ["bitset", "bitvec", "container", "data-structure", "no_std"]
categories = ["data-structures"]
