name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install 1.68 --profile minimal --component clippy
    - run: cargo +1.68 clippy --workspace --all-features --all-targets -- --deny warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal --component rustfmt
    - run: cargo fmt --check
